### ISSUE TITLE
import txt format data

### ISSUE THREAD

**Issue by waynelapierre** [hannesmuehleisen/MonetDBLite-R#27]
I noticed that MonetDBLite can only import csv file data, could you add support for txt (fixed width and tab delimited) format data?

**Comment by hannesmuehleisen** [comment]
This is already supported. The tab-delimited files can be imported by using `dbWriteTable(conn, "table", "file.tsv", delim="\t")`, the file name really does not matter here. For fixed-width formats, you can use SQL directly, like so: 

````R
tf <- tempfile()
gdata::write.fwf(mtcars, tf, colnames = FALSE)
dbSendQuery(con, "CREATE TABLE mtcars (mpg DOUBLE PRECISION, cyl DOUBLE PRECISION, disp DOUBLE PRECISION, hp DOUBLE PRECISION, drat DOUBLE PRECISION, wt DOUBLE PRECISION, qsec DOUBLE PRECISION, vs DOUBLE PRECISION, am DOUBLE PRECISION, gear DOUBLE PRECISION, carb DOUBLE PRECISION)")
dbExecute(con, paste0("COPY INTO mtcars FROM '", tf, "' FWF (4, 2, 6, 4, 5, 6, 6, 2, 2, 2, 2)"))
````
The `FWF` parameter indicates the widths of the fields. A bit more work since you have to manually construct the `CREATE TABLE` statement.
